# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-19 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows', '0002_auto_20190816_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='price',
            field=models.DecimalField(decimal_places=2, default=19.99, max_digits=999),
        ),
    ]
